FROM node:latest as build-deps
WORKDIR /src
COPY ./frontend /src
RUN yarn
RUN yarn build .

# Second stage - start webserver

FROM nginx:latest

VOLUME /data

WORKDIR /src
COPY --from=build-deps /src/build /usr/share/nginx/html

COPY ./setup/nginx /etc/nginx/