FROM node:14

WORKDIR /home/signalingServer
ARG VIRTUAL_PORT

ENV VIRTUAL_PORT=${VIRTUAL_PORT}
EXPOSE ${VIRTUAL_PORT}
CMD npm install && npm install -g nodemon && PORT=${VIRTUAL_PORT} nodemon chatserver.js